const applications = [
  {
    name: "Computer Science",
    university: "Stanford University",
    country: "USA",
    duration: 4,
    cost: 50000,
    deadline: "2024-12-01",
    language: "English",
  },
  {
    name: "Economics",
    university: "London School of Economics",
    country: "UK",
    duration: 3,
    cost: 45000,
    deadline: "2024-11-15",
    language: "English",
  },
  {
    name: "Medicine",
    university: "Harvard Medical School",
    country: "USA",
    duration: 5,
    cost: 70000,
    deadline: "2024-12-10",
    language: "English",
  },
  {
    name: "Business Administration",
    university: "INSEAD",
    country: "France",
    duration: 2,
    cost: 60000,
    deadline: "2024-10-20",
    language: "English",
  },
  {
    name: "Mathematics",
    university: "University of Cambridge",
    country: "UK",
    duration: 3,
    cost: 48000,
    deadline: "2024-11-30",
    language: "English",
  },
  {
    name: "Engineering",
    university: "MIT",
    country: "USA",
    duration: 4,
    cost: 55000,
    deadline: "2024-12-05",
    language: "English",
  },
  {
    name: "Physics",
    university: "ETH Zurich",
    country: "Switzerland",
    duration: 3,
    cost: 52000,
    deadline: "2024-11-25",
    language: "English",
  },
  {
    name: "Architecture",
    university: "Delft University of Technology",
    country: "Netherlands",
    duration: 5,
    cost: 48000,
    deadline: "2024-12-15",
    language: "English",
  },
  {
    name: "Chemistry",
    university: "University of Tokyo",
    country: "Japan",
    duration: 4,
    cost: 46000,
    deadline: "2024-11-10",
    language: "Japanese",
  },
  {
    name: "Psychology",
    university: "University of Melbourne",
    country: "Australia",
    duration: 3,
    cost: 42000,
    deadline: "2024-11-20",
    language: "English",
  },
  {
    name: "Linguistics",
    university: "University of Helsinki",
    country: "Finland",
    duration: 2,
    cost: 38000,
    deadline: "2024-11-05",
    language: "Finnish",
  },
  {
    name: "Law",
    university: "Yale Law School",
    country: "USA",
    duration: 3,
    cost: 62000,
    deadline: "2024-12-03",
    language: "English",
  },
  {
    name: "Environmental Science",
    university: "Australian National University",
    country: "Australia",
    duration: 4,
    cost: 44000,
    deadline: "2024-11-12",
    language: "English",
  },
  {
    name: "History",
    university: "Sorbonne University",
    country: "France",
    duration: 3,
    cost: 40000,
    deadline: "2024-10-30",
    language: "French",
  },
  {
    name: "Sociology",
    university: "University of California, Berkeley",
    country: "USA",
    duration: 2,
    cost: 48000,
    deadline: "2024-12-08",
    language: "English",
  },
  {
    name: "Education",
    university: "University of London",
    country: "UK",
    duration: 2,
    cost: 36000,
    deadline: "2024-11-22",
    language: "English",
  },
  {
    name: "Anthropology",
    university: "University of Chicago",
    country: "USA",
    duration: 3,
    cost: 54000,
    deadline: "2024-12-18",
    language: "English",
  },
  {
    name: "Philosophy",
    university: "University of Oxford",
    country: "UK",
    duration: 4,
    cost: 50000,
    deadline: "2024-11-28",
    language: "English",
  },
  {
    name: "Geology",
    university: "University of Oslo",
    country: "Norway",
    duration: 3,
    cost: 46000,
    deadline: "2024-11-15",
    language: "Norwegian",
  },
  {
    name: "Political Science",
    university: "University of California, San Diego",
    country: "USA",
    duration: 2,
    cost: 49000,
    deadline: "2024-12-07",
    language: "English",
  },
  {
    name: "Music",
    university: "Juilliard School",
    country: "USA",
    duration: 4,
    cost: 58000,
    deadline: "2024-12-20",
    language: "English",
  },
  {
    name: "Dentistry",
    university: "Tokyo Medical and Dental University",
    country: "Japan",
    duration: 5,
    cost: 65000,
    deadline: "2024-11-25",
    language: "Japanese",
  },
  {
    name: "Film Studies",
    university: "University of Southern California",
    country: "USA",
    duration: 2,
    cost: 54000,
    deadline: "2024-12-15",
    language: "English",
  },
  {
    name: "Agriculture",
    university: "Cornell University",
    country: "USA",
    duration: 3,
    cost: 47000,
    deadline: "2024-12-10",
    language: "English",
  },
  {
    name: "Religious Studies",
    university: "Hebrew University of Jerusalem",
    country: "Israel",
    duration: 2,
    cost: 42000,
    deadline: "2024-11-30",
    language: "Hebrew",
  },
  {
    name: "Journalism",
    university: "Columbia University",
    country: "USA",
    duration: 1,
    cost: 40000,
    deadline: "2024-12-05",
    language: "English",
  },
  {
    name: "Nutrition",
    university: "University of Sydney",
    country: "Australia",
    duration: 2,
    cost: 38000,
    deadline: "2024-11-18",
    language: "English",
  },
  {
    name: "Fashion Design",
    university: "Central Saint Martins",
    country: "UK",
    duration: 3,
    cost: 49000,
    deadline: "2024-11-28",
    language: "English",
  },
  {
    name: "Physical Therapy",
    university: "University of Pittsburgh",
    country: "USA",
    duration: 3,
    cost: 52000,
    deadline: "2024-12-15",
    language: "English",
  },
  {
    name: "Criminal Justice",
    university: "University of California, Irvine",
    country: "USA",
    duration: 2,
    cost: 45000,
    deadline: "2024-12-02",
    language: "English",
  },
  {
    name: "International Relations",
    university: "Georgetown University",
    country: "USA",
    duration: 2,
    cost: 56000,
    deadline: "2024-12-08",
    language: "English",
  },
  {
    name: "Sports Science",
    university: "University of Queensland",
    country: "Australia",
    duration: 2,
    cost: 43000,
    deadline: "2024-11-25",
    language: "English",
  },
  {
    name: "Astrophysics",
    university: "University of Cambridge",
    country: "UK",
    duration: 4,
    cost: 55000,
    deadline: "2024-11-10",
    language: "English",
  },
  {
    name: "Biomedical Engineering",
    university: "Johns Hopkins University",
    country: "USA",
    duration: 3,
    cost: 59000,
    deadline: "2024-12-20",
    language: "English",
  },
  {
    name: "Public Health",
    university: "University of Washington",
    country: "USA",
    duration: 2,
    cost: 48000,
    deadline: "2024-12-12",
    language: "English",
  },
  {
    name: "Veterinary Medicine",
    university: "University of Edinburgh",
    country: "UK",
    duration: 5,
    cost: 62000,
    deadline: "2024-11-30",
    language: "English",
  },
  {
    name: "Urban Planning",
    university: "Massachusetts Institute of Technology",
    country: "USA",
    duration: 3,
    cost: 54000,
    deadline: "2024-12-18",
    language: "English",
  },
  {
    name: "Hospitality Management",
    university: "École hôtelière de Lausanne",
    country: "Switzerland",
    duration: 2,
    cost: 50000,
    deadline: "2024-12-01",
    language: "English",
  },
  {
    name: "Computer Engineering",
    university: "National University of Singapore",
    country: "Singapore",
    duration: 4,
    cost: 57000,
    deadline: "2024-12-10",
    language: "English",
  },
  {
    name: "Marine Biology",
    university: "James Cook University",
    country: "Australia",
    duration: 3,
    cost: 46000,
    deadline: "2024-11-20",
    language: "English",
  },
  {
    name: "Fine Arts",
    university: "Royal College of Art",
    country: "UK",
    duration: 2,
    cost: 43000,
    deadline: "2024-11-05",
    language: "English",
  },
  {
    name: "Civil Engineering",
    university: "University of California, Berkeley",
    country: "USA",
    duration: 4,
    cost: 59000,
    deadline: "2024-12-15",
    language: "English",
  },
  {
    name: "Theater Studies",
    university: "New York University",
    country: "USA",
    duration: 3,
    cost: 48000,
    deadline: "2024-12-05",
    language: "English",
  },
  {
    name: "Geography",
    university: "University of British Columbia",
    country: "Canada",
    duration: 3,
    cost: 50000,
    deadline: "2024-11-25",
    language: "English",
  },
  {
    name: "Fashion Merchandising",
    university: "Parsons School of Design",
    country: "USA",
    duration: 2,
    cost: 45000,
    deadline: "2024-12-08",
    language: "English",
  },
  {
    name: "Industrial Design",
    university: "Rhode Island School of Design",
    country: "USA",
    duration: 4,
    cost: 56000,
    deadline: "2024-12-18",
    language: "English",
  },
  {
    name: "Information Technology",
    university: "ETH Zurich",
    country: "Switzerland",
    duration: 2,
    cost: 52000,
    deadline: "2024-12-20",
    language: "English",
  },
  {
    name: "Environmental Engineering",
    university: "University of California, Davis",
    country: "USA",
    duration: 3,
    cost: 51000,
    deadline: "2024-12-12",
    language: "English",
  },
  {
    name: "Art History",
    university: "Courtauld Institute of Art",
    country: "UK",
    duration: 3,
    cost: 47000,
    deadline: "2024-11-30",
    language: "English",
  },
  {
    name: "Social Work",
    university: "University of Michigan",
    country: "USA",
    duration: 2,
    cost: 48000,
    deadline: "2024-12-10",
    language: "English",
  },
  {
    name: "Biology",
    university: "University of California, San Francisco",
    country: "USA",
    duration: 4,
    cost: 62000,
    deadline: "2024-12-02",
    language: "English",
  },
  {
    name: "Drama",
    university: "Guildhall School of Music & Drama",
    country: "UK",
    duration: 2,
    cost: 44000,
    deadline: "2024-11-18",
    language: "English",
  },
  {
    name: "Philology",
    university: "University of Warsaw",
    country: "Poland",
    duration: 3,
    cost: 38000,
    deadline: "2024-11-10",
    language: "Polish",
  },
  {
    name: "Development Studies",
    university: "University of Sussex",
    country: "UK",
    duration: 1,
    cost: 35000,
    deadline: "2024-11-22",
    language: "English",
  },
  {
    name: "Criminology",
    university: "University of Pennsylvania",
    country: "USA",
    duration: 3,
    cost: 57000,
    deadline: "2024-12-18",
    language: "English",
  },
  {
    name: "Neuroscience",
    university: "University of Amsterdam",
    country: "Netherlands",
    duration: 4,
    cost: 54000,
    deadline: "2024-12-08",
    language: "English",
  },
  {
    name: "Tourism Management",
    university: "University of Otago",
    country: "New Zealand",
    duration: 2,
    cost: 42000,
    deadline: "2024-11-25",
    language: "English",
  },
  {
    name: "Counseling Psychology",
    university: "Boston University",
    country: "USA",
    duration: 2,
    cost: 49000,
    deadline: "2024-12-15",
    language: "English",
  },
];

export default applications;
